import type { Place } from "./types";

// EDIT ME — these are placeholders for Phil's actual life.
// For each Place set: real coordinates, real answer to the numeric question,
// real photo in /public/photos/. Sit down with the groomsmen and fill in
// the truth before the party.
export const PHIL_PLACES: Place[] = [
  {
    id: "p1",
    title: "Phil's childhood home",
    pills: ["San Diego, CA", "1996 – 2014"],
    location: { lat: 32.7157, lng: -117.1611, label: "San Diego, CA" },
    numericQuestion: {
      label: "Age Phil moved in",
      prompt: "How old was Phil when his family moved here from Israel?",
      answer: 4,
      unitSuffix: "yrs",
      min: 0,
      max: 15,
      step: 1,
    },
    funFact: "He still claims he remembers the flight.",
  },
  {
    id: "p2",
    title: "The NYU dorm",
    pills: ["Greenwich Village, NYC", "Freshman year"],
    location: { lat: 40.7295, lng: -73.9965, label: "NYU, Manhattan" },
    numericQuestion: {
      label: "Monthly housing cost",
      prompt: "What did the school charge Phil per month for this glorified shoebox?",
      answer: 1800,
      unitPrefix: "$",
      min: 500,
      max: 5000,
      step: 50,
    },
    funFact: "He had a roommate who set off the fire alarm 11 times.",
  },
  {
    id: "p3",
    title: "Diana & Ross in Melbourne",
    pills: ["Melbourne, Australia", "With the boyfriend"],
    location: { lat: -37.8136, lng: 144.9631, label: "Melbourne, Australia" },
    numericQuestion: {
      label: "Miles from Santa Monica",
      prompt: "How far does Phil have to fly to see his sister?",
      answer: 7930,
      unitSuffix: "mi",
      min: 1000,
      max: 12000,
      step: 100,
    },
    funFact: "He's been twice. Once for her birthday, once just because.",
  },
  {
    id: "p4",
    title: "Phil's Santa Monica apartment",
    pills: ["Santa Monica, CA", "Current"],
    location: { lat: 34.0195, lng: -118.4912, label: "Santa Monica, CA" },
    numericQuestion: {
      label: "Monthly rent",
      prompt: "How much does Phil hand over every month for the privilege of saying he lives here?",
      answer: 3800,
      unitPrefix: "$",
      min: 1500,
      max: 8000,
      step: 50,
    },
    funFact: "The view is of a parking garage.",
  },
  {
    id: "p5",
    title: "The proposal",
    pills: ["Top secret", "October 2024"],
    location: { lat: 33.6846, lng: -117.8265, label: "Newport Beach, CA" },
    numericQuestion: {
      label: "Times Phil cried that day",
      prompt: "How many times did Phil tear up between waking up and the \"yes\"?",
      answer: 4,
      unitSuffix: "times",
      min: 0,
      max: 20,
      step: 1,
    },
    funFact: "He practiced the speech in the bathroom 9 times. Forgot it anyway.",
  },
  {
    id: "p6",
    title: "Cisco HQ",
    pills: ["San Jose, CA", "Sales Operations"],
    location: { lat: 37.4047, lng: -121.9787, label: "Cisco HQ, San Jose" },
    numericQuestion: {
      label: "Years Phil has worked at Cisco",
      prompt: "How long has Phil been a corporate sales-ops grinder?",
      answer: 5,
      unitSuffix: "yrs",
      min: 0,
      max: 15,
      step: 1,
    },
    funFact: "His Slack status hasn't been changed since 2022.",
  },
  {
    id: "p7",
    title: "Phil's birthplace",
    pills: ["Israel", "Toddler years"],
    location: { lat: 32.0853, lng: 34.7818, label: "Tel Aviv, Israel" },
    numericQuestion: {
      label: "Year Phil was born",
      prompt: "What year did the world get blessed with Phil?",
      answer: 1992,
      min: 1985,
      max: 2000,
      step: 1,
    },
    funFact: "His grandma still calls him by his Hebrew name.",
  },
  {
    id: "p8",
    title: "Joshua Tree — right here, right now",
    pills: ["Bachelor party HQ", "Today"],
    location: { lat: 33.8814, lng: -115.9, label: "Joshua Tree, CA" },
    numericQuestion: {
      label: "Guests at the bachelor party",
      prompt: "How many of us did Phil drag out into the desert?",
      answer: 20,
      unitSuffix: "guests",
      min: 5,
      max: 40,
      step: 1,
    },
    funFact: "Phil insisted on the Airbnb with the bidet.",
  },
];
