import type { Question } from "./types";

// EDIT ME: Replace placeholder answers with the real ones before the party.
// Drop matching photos in /public/photos and reference them as `/photos/file.jpg`.
export const PHIL_QUESTIONS: Question[] = [
  {
    id: "q1",
    kind: "closest",
    prompt: "How old was Phil when his family moved from Israel to San Diego?",
    unit: "years old",
    answer: 4,
    funFact: "He still claims he remembers the flight.",
  },
  {
    id: "q2",
    kind: "higher_lower",
    prompt: "Phil's monthly rent in Santa Monica.",
    statement: "Is his rent higher or lower than $3,500/month?",
    reference: 3500,
    unit: "USD",
    answer: "higher",
  },
  {
    id: "q3",
    kind: "yes_no",
    prompt: "Has Phil ever visited Diana in Melbourne?",
    answer: "yes",
    funFact: "Twice — once for her birthday, once just because.",
  },
  {
    id: "q4",
    kind: "closest",
    prompt: "How many years has Phil been at Cisco?",
    unit: "years",
    answer: 5,
  },
  {
    id: "q5",
    kind: "multiple_choice",
    prompt: "What was Phil's major at NYU?",
    choices: ["Business", "Computer Science", "Economics", "Communications"],
    answerIndex: 0,
  },
  {
    id: "q6",
    kind: "yes_no",
    prompt: "Did Phil propose to Michelle in Santa Monica?",
    answer: "no",
    funFact: "It was actually on a trip — ask him about it.",
  },
  {
    id: "q7",
    kind: "closest",
    prompt: "Year Phil and Michelle first met.",
    answer: 2019,
  },
  {
    id: "q8",
    kind: "higher_lower",
    prompt: "Distance from Santa Monica to Diana's place in Melbourne.",
    statement: "Higher or lower than 8,000 miles?",
    reference: 8000,
    unit: "miles",
    answer: "higher",
  },
  {
    id: "q9",
    kind: "multiple_choice",
    prompt: "Which Cisco team does Phil actually work on?",
    choices: [
      "Sales Operations",
      "Customer Success",
      "Product Marketing",
      "Engineering",
    ],
    answerIndex: 0,
  },
  {
    id: "q10",
    kind: "closest",
    prompt: "How many countries has Phil been to?",
    unit: "countries",
    answer: 22,
  },
  {
    id: "q11",
    kind: "yes_no",
    prompt: "Has Phil ever gotten an F in a class?",
    answer: "no",
  },
  {
    id: "q12",
    kind: "closest",
    prompt: "Phil's age when he had his first kiss.",
    unit: "years old",
    answer: 14,
    hint: "Be generous.",
  },
  {
    id: "q13",
    kind: "multiple_choice",
    prompt: "Diana lives in Melbourne with Ross. What does Ross do?",
    choices: ["Doctor", "Engineer", "Teacher", "Chef"],
    answerIndex: 1,
  },
  {
    id: "q14",
    kind: "higher_lower",
    prompt: "Phil's all-time longest single Slack message at Cisco.",
    statement: "Higher or lower than 500 words?",
    reference: 500,
    unit: "words",
    answer: "higher",
    funFact: "He once sent a 1,200-word message about a deal pipeline.",
  },
  {
    id: "q15",
    kind: "closest",
    prompt: "How many groomsmen are in Phil's wedding party?",
    answer: 7,
  },
];
