import type { Question } from "./types";

// EDIT ME — these answers are placeholders. Sit down with the groomsmen,
// fill in the truth, then redeploy. Add `image: "/photos/foo.jpg"` to any
// question to show a photo with it.
export const PHIL_QUESTIONS: Question[] = [
  {
    id: "q1",
    kind: "closest",
    prompt: "Phil's hookup count before Michelle.",
    answer: 18,
    funFact: "He once tried to write them down on a napkin and lost it at the bar.",
  },
  {
    id: "q2",
    kind: "yes_no",
    prompt: "Has Phil ever puked in a moving Uber?",
    answer: "yes",
    funFact: "Cleaning fee: $150. The driver still 5-starred him.",
  },
  {
    id: "q3",
    kind: "higher_lower",
    prompt: "Phil's biggest single-night bar tab — ever.",
    statement: "Higher or lower than $500?",
    reference: 500,
    unit: "USD",
    answer: "higher",
  },
  {
    id: "q4",
    kind: "yes_no",
    prompt: "Has Phil ever been physically thrown out of a bar?",
    answer: "yes",
    funFact: "By a bouncer who was, regrettably, smaller than him.",
  },
  {
    id: "q5",
    kind: "closest",
    prompt: "Phil's actual age at his first kiss. Be honest.",
    unit: "years old",
    answer: 16,
    hint: "Be generous. Or don't.",
  },
  {
    id: "q6",
    kind: "multiple_choice",
    prompt: "Phil's go-to karaoke song when he's three drinks deep.",
    choices: [
      "Mr. Brightside",
      "Wonderwall",
      "Sweet Caroline",
      "Wagon Wheel",
    ],
    answerIndex: 0,
  },
  {
    id: "q7",
    kind: "higher_lower",
    prompt: "Phil's longest dating dry spell, pre-Michelle.",
    statement: "Higher or lower than 14 months?",
    reference: 14,
    unit: "months",
    answer: "higher",
  },
  {
    id: "q8",
    kind: "yes_no",
    prompt: "Has Phil ever ghosted a date who was already sitting at the restaurant?",
    answer: "yes",
  },
  {
    id: "q9",
    kind: "closest",
    prompt: "Number of Diana's friends Phil has shamelessly shot his shot at.",
    answer: 4,
    funFact: "Diana has a running blacklist on her phone.",
  },
  {
    id: "q10",
    kind: "multiple_choice",
    prompt: "Phil's signature 3am drunk food.",
    choices: [
      "In-N-Out (Animal Style)",
      "Taco Bell quesarito",
      "Gas station hot dog",
      "Cold leftover sushi",
    ],
    answerIndex: 1,
  },
  {
    id: "q11",
    kind: "yes_no",
    prompt: "Has Phil ever drunk-dialed his Russian grandma and then lied about it the next day?",
    answer: "yes",
    funFact: "She still asks him about \"that nice girl\" he was crying about.",
  },
  {
    id: "q12",
    kind: "higher_lower",
    prompt: "Phil's worst grade at NYU.",
    statement: "Higher or lower than a C-?",
    reference: 0,
    answer: "lower",
    funFact: "He still emails the professor about extra credit.",
  },
  {
    id: "q13",
    kind: "closest",
    prompt: "Number of times Phil has cried in front of Michelle.",
    answer: 11,
    funFact: "Six of them were during the same Pixar movie.",
  },
  {
    id: "q14",
    kind: "multiple_choice",
    prompt: "Worst thing ever found in Phil's car.",
    choices: [
      "Used vape",
      "Month-old gym shorts",
      "A girl's earring (not Michelle's)",
      "Parking ticket from 2019",
    ],
    answerIndex: 2,
  },
  {
    id: "q15",
    kind: "yes_no",
    prompt: "Has Phil ever joined a Cisco Zoom hungover, camera on, hoping nobody would notice?",
    answer: "yes",
    funFact: "His VP brought it up in his next 1-on-1.",
  },
];
