import type { Round } from "./types";

// EDIT ME — placeholder answers throughout. Calibrate with the groomsmen
// before the party. Add photos in /public/photos/ and reference like
// `image: "/photos/baby-phil.jpg"`.
export const PHIL_ROUNDS: Round[] = [
  {
    kind: "map_number",
    id: "r1",
    title: "Phil's childhood home",
    pills: ["San Diego, CA", "1996 – 2014"],
    location: { lat: 32.7157, lng: -117.1611, label: "San Diego, CA" },
    numericQuestion: {
      label: "Age Phil moved in",
      prompt: "How old was Phil when his family moved here from Israel?",
      answer: 4,
      unitSuffix: "yrs",
      min: 0,
      max: 15,
      step: 1,
    },
    funFact: "He still claims he remembers the flight.",
  },
  {
    kind: "photo_choice",
    id: "r2",
    title: "Spot baby Phil",
    prompt: "Which of these screaming Russian babies is Phil?",
    choices: [
      { image: "/photos/baby-a.jpg", label: "A" },
      { image: "/photos/baby-b.jpg", label: "B" },
      { image: "/photos/baby-c.jpg", label: "C" },
      { image: "/photos/baby-d.jpg", label: "D" },
    ],
    answerIndex: 1,
    funFact: "Phil insists this was his \"good angle\" era.",
  },
  {
    kind: "multiple_choice",
    id: "r3",
    title: "NYU days",
    prompt: "What did Phil actually major in?",
    choices: ["Business", "Computer Science", "Economics", "Communications"],
    answerIndex: 0,
    pills: ["Greenwich Village", "Class of '14"],
  },
  {
    kind: "higher_lower",
    id: "r4",
    title: "Santa Monica rent check",
    prompt: "Phil's monthly rent.",
    statement: "Higher or lower than $3,500?",
    reference: 3500,
    unitPrefix: "$",
    answer: "higher",
    pills: ["Santa Monica, CA", "Current"],
    funFact: "The view is of a parking garage.",
  },
  {
    kind: "map_number",
    id: "r5",
    title: "Diana & Ross in Melbourne",
    pills: ["Melbourne, Australia", "With the boyfriend"],
    location: { lat: -37.8136, lng: 144.9631, label: "Melbourne, Australia" },
    numericQuestion: {
      label: "Miles from Santa Monica",
      prompt: "How far does Phil have to fly to see his sister?",
      answer: 7930,
      unitSuffix: "mi",
      min: 1000,
      max: 12000,
      step: 100,
    },
    funFact: "He's been twice. Once for her birthday, once just because.",
  },
  {
    kind: "yes_no",
    id: "r6",
    title: "Confessional",
    prompt: "Has Phil ever puked in a moving Uber?",
    answer: "yes",
    funFact: "Cleaning fee: $150. The driver still 5-starred him.",
  },
  {
    kind: "number",
    id: "r7",
    title: "Phil's pre-Michelle body count",
    pills: ["Be generous"],
    numericQuestion: {
      label: "Hookups before Michelle",
      prompt: "How many partners did Phil have before settling down?",
      answer: 18,
      min: 0,
      max: 60,
      step: 1,
    },
    funFact: "He once tried writing them down on a napkin. Lost it at the bar.",
  },
  {
    kind: "photo_choice",
    id: "r8",
    title: "Phil's current apartment",
    prompt: "Which of these is Phil's actual Santa Monica spot?",
    choices: [
      { image: "/photos/apt-a.jpg" },
      { image: "/photos/apt-b.jpg" },
      { image: "/photos/apt-c.jpg" },
      { image: "/photos/apt-d.jpg" },
    ],
    answerIndex: 2,
  },
  {
    kind: "map_number",
    id: "r9",
    title: "The proposal",
    pills: ["Top secret", "October 2024"],
    location: { lat: 33.6846, lng: -117.8265, label: "Newport Beach, CA" },
    numericQuestion: {
      label: "Times Phil cried that day",
      prompt: "How many times did Phil tear up between waking up and the \"yes\"?",
      answer: 4,
      unitSuffix: "times",
      min: 0,
      max: 20,
      step: 1,
    },
    funFact: "He practiced the speech 9 times in the bathroom. Forgot it anyway.",
  },
  {
    kind: "multiple_choice",
    id: "r10",
    title: "Karaoke crimes",
    prompt: "Phil's go-to song after three drinks?",
    choices: ["Mr. Brightside", "Wonderwall", "Sweet Caroline", "Wagon Wheel"],
    answerIndex: 0,
    funFact: "He has been banned from one karaoke bar for this exact song.",
  },
  {
    kind: "higher_lower",
    id: "r11",
    title: "Biggest single-night bar tab",
    prompt: "Phil's all-time biggest bar tab.",
    statement: "Higher or lower than $500?",
    reference: 500,
    unitPrefix: "$",
    answer: "higher",
    funFact: "He still has the receipt in his wallet. Why.",
  },
  {
    kind: "map_number",
    id: "r12",
    title: "Right here, right now",
    pills: ["Bachelor party HQ", "Today"],
    location: { lat: 33.8814, lng: -115.9, label: "Joshua Tree, CA" },
    numericQuestion: {
      label: "Guests at the bachelor party",
      prompt: "How many of us did Phil drag into the desert?",
      answer: 20,
      unitSuffix: "guests",
      min: 5,
      max: 40,
      step: 1,
    },
    funFact: "Phil insisted on the Airbnb with the bidet.",
  },
];
